In [1]:
import pandas as pd
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [3]:
data={"Name":["A","B","C"],
      "Age":[16,17,19],
      "Marks":[40,35,29]}
df=pd.DataFrame(data)
print(df)
df.head()

  Name  Age  Marks
0    A   16     40
1    B   17     35
2    C   19     29


,Name,Age,Marks
0,A,16,40
1,B,17,35
2,C,19,29


import numpy as np

***Basics***


In [4]:
import numpy as np
a=np.array([1,2,3],dtype='int32')
print(a)


[1 2 3]


In [5]:
b=np.array([[1,2,3],[6,9.0,2.4]])
print(b)

[[1.  2.  3. ]
 [6.  9.  2.4]]


In [6]:
import numpy as np
c=np.array([[[1,2,3],[6,9.0,2.4],[8,9,10]]])
print(c)
print(c.ndim)

[[[ 1.   2.   3. ]
  [ 6.   9.   2.4]
  [ 8.   9.  10. ]]]
3


In [7]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [8]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get Type
a.dtype

dtype('int32')

In [10]:
#Get size
a.size  # number of elements

3

In [11]:
#Get size
a.itemsize # bytes per element

4

In [12]:
#get total_size
a=np.array([1,2,3,4],dtype='int16')
a.nbytes     # total bytes = size × itemsize

8

**Accessing/Changing specific elements,rows,columns,etc** 

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
#Get a specific element[r,c]
a[1,5]

np.int64(13)

In [15]:
#Get a specific row
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[0,3:4]

array([4])

In [16]:
a[:,2]

array([ 3, 10])

In [17]:
#Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [18]:
a[1,5]=20
print(a)
a[:,2]=[1,2]
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3-d example**


In [19]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
#Get specific element(work outside in)
b[0,1,1]

np.int64(4)

In [21]:
import numpy as np
#replace
b = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(b)
b[:, 1, :] = [[9,9,9],
              [8,8,8]]
print(b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


**Initialising different types of Arrays**


In [22]:
#all 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [24]:
#any other number
import numpy as np
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
#any other number (full_like)
a=([4,3,7],[9,10,7])
np.full_like(a,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [26]:
#Random decimal numbers
a=np.array([[2,3],[5,7]])
np.random.random_sample(a.shape)

array([[0.32238367, 0.40275458],
       [0.43259263, 0.35825961]])

In [27]:
np.random.rand(4,2)

array([[0.83210465, 0.44009787],
       [0.97065584, 0.40186256],
       [0.04668224, 0.70293027],
       [0.13819218, 0.87796476]])

In [28]:
#random integer values
np.random.randint(4,8,size=(3,3))

array([[5, 7, 5],
       [4, 6, 4],
       [4, 6, 7]], dtype=int32)

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.array([[1,2,3]])
print(arr.ndim)
r1=np.repeat(arr,3,axis=0) #(arr,repeats,axis)
print(r1)

2
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
output=np.zeros((5,5))
print(output)
z=np.ones((3,3))
z[1,1]=2
print(z)
output[1:4,1:4]=z
print(output)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**Be careful when copying arrays!!!**


In [33]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [34]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


***Mathematics***

In [35]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a-2

array([-1,  0,  1,  2])

In [38]:
a*2

array([2, 4, 6, 8])

In [39]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [41]:
a**2

array([ 1,  4,  9, 16])

In [42]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [44]:
#For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


**Linear Algebra**


In [45]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

**Statistics**

In [47]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.min(stats,axis=0)

array([1, 2, 3])

In [49]:
np.max(stats,axis=1)

array([3, 6])

In [50]:
stats=np.array([[1,2,3],[4,5,6]])
np.sum(stats,axis=1)

array([ 6, 15])

In [51]:
np.sum(stats,axis=0)


array([5, 7, 9])

**Reorganizing arrays**

In [52]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [53]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
#Horizontal stacks
h1=np.ones((2,4))
print(h1)
h2=np.zeros((2,2))
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Miscellaneous**


*load data from file*

In [76]:
np.genfromtxt(r'C:\Home\M DEEIKA\.conda\text.txt', delimiter='*')
print(data)

FileNotFoundError: C:\Home\M DEEIKA\.conda\text.txt not found.

**Boolean masking and advanced indexing**


In [77]:
filedata>50

NameError: name 'filedata' is not defined

In [78]:
filedata[filedata>50]


NameError: name 'filedata' is not defined

In [79]:
#you can index with a list in numpy
a=np.array([196,56,78,23,90])
a[[1,2,8]]

IndexError: index 8 is out of bounds for axis 0 with size 5

In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))   # Average
print(np.median(arr)) # Middle value
print(np.std(arr))    # Standard deviation
print(np.var(arr))    # Variance

3.0
3.0
1.4142135623730951
2.0


In [60]:
arr = np.array([1, 2, 10, 3, 4])

print(np.mean(arr))   # (1+2+10+3+4)/5 = 4
print(np.median(arr)) # sorted → [1,2,3,4,10] → 3

4.0
3.0


In [61]:
arr = np.array([1, 2, 3, 4, 5])

print(np.var(arr))  # Variance
print(np.std(arr))  # Standard deviation

2.0
1.4142135623730951


In [62]:
arr = np.array([10, 20, 5, 40])

print(np.max(arr))  # 40
print(np.min(arr))  # 5
print(np.ptp(arr))  # range = max - min = 35

40
5
35


In [63]:
arr = np.array([10, 20, 30, 40, 50])

print(np.percentile(arr, 25))  # 25th percentile
print(np.percentile(arr, 50))  # median
print(np.percentile(arr, 90))  # 90th percentile

20.0
30.0
46.0


In [64]:
arr = np.array(["hello", "world"])

print(np.char.upper(arr))
print(np.char.capitalize(arr))

['HELLO' 'WORLD']
['Hello' 'World']


In [65]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))  # [1 2 3 4]
print(np.tile(a, 2))           # [1 2 1 2]

[1 2 3 4]
[1 2 1 2]


In [66]:
arr = np.array(["hello", "world"])

print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [67]:
arr = np.array(["hello world"])

print(np.char.split(arr))  

joined = np.char.join("-", arr)
print(joined)

[list(['hello', 'world'])]
['h-e-l-l-o- -w-o-r-l-d']


In [68]:
arr = np.array(["hello world"])

print(np.char.replace(arr, "world", "NumPy"))

['hello NumPy']


In [69]:
arr = np.array(["hello", "123", "abc123"])

print(np.char.isalpha(arr))  # letters only?
print(np.char.isdigit(arr))  # digits only?
print(np.char.isalnum(arr))  # alphanumeric?

[ True False False]
[False  True False]
[ True  True  True]


In [70]:
arr = np.array([5, 10, 15, 20, 25])
print(np.mean(arr))
print(np.max(arr))
print(np.percentile(arr,75))
print(np.std(arr))

15.0
25
20.0
7.0710678118654755


In [71]:
import numpy as np
arr = np.array([1, 2, 2, 3, 4, 4])
print(np.unique(arr))

[1 2 3 4]


In [72]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

np.union1d(a, b)

array([1, 2, 3, 4, 5])

In [73]:
np.intersect1d(a, b)

array([3])

In [74]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([8, 13])

x = np.linalg.solve(A, b)
print(x)

[2.2 3.6]


In [75]:
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
